// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {backend} from '../models';

export function AddActivityFromPomo(arg1:store.Activity):Promise<number>;

export function GetPomoMonthReport(arg1:string):Promise<Array<store.SessionDbRowMonth>>;

export function GetPomoWeekReport(arg1:string):Promise<Array<store.SessionDbRow>>;

export function GetPomoYearReport(arg1:string):Promise<Array<store.SessionDbRowYear>>;

export function GetPomos(arg1:string):Promise<Array<store.SessionDbRow>>;

export function Greet(arg1:string):Promise<string>;

export function StartPomo(arg1:store.Session):Promise<number>;

export function UpdatePomoSecondsLeft(arg1:backend.UpdateSessionSecondsLeft):Promise<boolean>;
