// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDaysReport() {
  return window['go']['backend']['App']['GetDaysReport']();
}

export function GetPomoMonthReport(arg1) {
  return window['go']['backend']['App']['GetPomoMonthReport'](arg1);
}

export function GetPomoWeekReport(arg1) {
  return window['go']['backend']['App']['GetPomoWeekReport'](arg1);
}

export function GetPomoYearReport(arg1) {
  return window['go']['backend']['App']['GetPomoYearReport'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function StartPomo(arg1) {
  return window['go']['backend']['App']['StartPomo'](arg1);
}

export function UpdatePomoSecondsLeft(arg1) {
  return window['go']['backend']['App']['UpdatePomoSecondsLeft'](arg1);
}
