// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(arg1) {
  return window['go']['backend']['ConfigStore']['GetConfig'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['backend']['ConfigStore']['SetConfig'](arg1);
}
