// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetConfig(arg1:backend.AppState):Promise<backend.AppState>;

export function SetConfig(arg1:backend.AppState):Promise<void>;
