// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddActivityFromPomo(arg1:main.Activity):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function StartPomo(arg1:main.Session):Promise<number>;

export function UpdatePomoSecondsLeft(arg1:main.UpdateSessionSecondsLeft):Promise<boolean>;
